
- name: apt_key | Add Docker GPG key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: apt_repository | Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  become: yes

- name: apt | Install list of packages
  apt:
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
    state: present
    update_cache: yes
  become: yes

- name: get_url | Download and install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.23.1/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 0755
  become: yes

- name: user | adding docker users (for use without sudo)
  user:
    name: vagrant
    append: yes
    groups: docker
  become: true

# - name: pause | Pause nach der Dockerinstallation, damit sich Netz einpendelt.
#   pause:
#     prompt: "Pause nach der Dockerinstallation, damit sich Netz einpendeln kann."
#     seconds: 5