#!/usr/bin/env ruby

# We use a config file for user parameters.
configFile='./config.yml'
# In Ruby we need a YAML module to serialize the yaml string
require 'yaml'
getVar = YAML.load_file(configFile) 

BOX_IMAGE         = getVar['BOX_IMAGE']
NUMBER_OF_MANGERS = getVar['NUMBER_OF_MANGERS']

####################################################################################

Vagrant.configure("2") do |config|

  # Configure the hardware and the OS of the VMs.  
  config.vm.provider "virtualbox" do |vm|
    vm.memory = 768
    vm.cpus = 4
  end
  config.vm.box = BOX_IMAGE

  # Sync host folder with a folder within the VMs.
  config.vm.synced_folder "provision", "/home/vagrant/provision"
  # Basic configuration of Linux + Docker
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision/basic-config.yaml"    
    # Use python 3
    ansible.extra_vars = { ansible_python_interpreter: "/usr/bin/python3" }
  end

  # First config a VM as swarm manager1 
  config.vm.define "manager1" do |subconfig|
    subconfig.vm.hostname = "manager1"
    subconfig.vm.network "private_network", ip: "172.16.0.101"
    # Initialize swarm mode and store the join token 
    # in the file .join-manager-cmd.txt
    subconfig.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provision/swarm_init.yaml"    
    end
    # Install serveral services on manager1
    subconfig.vm.provision "shell", path: "provision/services/portainer/start-portainer.sh"
    subconfig.vm.provision "shell", path: "provision/services/visualizer/start-visualizer.sh"
  end

  # Configure manager 1..n and join the swarm
  (2..NUMBER_OF_MANGERS).each do |i|
    config.vm.define "manager#{i}" do |subconfig|
      subconfig.vm.hostname = "manager#{i}"
      subconfig.vm.network "private_network", ip: "172.16.0.#{100+i}"
      # Join the swarm
      subconfig.vm.provision "shell", path: "provision/swarm_join.sh"
    end
  end

end