# Docker-Compose für Visualizer

version: "3.5"

services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8050:8080"
    stop_grace_period: 30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]