Vagrant.configure("2") do |config|
  # Box settings
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.56.101"
  # Create a synced folder
  config.vm.synced_folder ".", "/var/sharedFolder", create: true
  # Provider settings
  config.vm.provider "virtualbox" do |vb|
  # Configure the memory
    vb.memory = 2048
  end
end