
Vagrant.configure("2") do |config|
  # Create virtual machine using ubuntu/trusty64 box
  config.vm.box = "ubuntu/trusty64"
  # Add a private network 
  config.vm.network "private_network", ip: "192.168.56.110"
end
