---
## Execute the docker ps command and register the result in docker_ps variable 
- name: Check if the visualization container is running
  command: docker ps
  register: docker_ps
  changed_when: false
## If our machine is the main manager and the visualizer container is not running, we run it 
#  with docker run command 
- name: Start visualization container
  command: docker run -it -d -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock dockersamples/visualizer
  when: >
        docker_ps.stdout.find('dockersamples/visualizer') == -1 and
        inventory_hostname == "manager1"
