########################################################################
#     Import variables from the configuration file
########################################################################
configFile='./config.yml'
# In Ruby this module is needed to serialize a Yaml string
require 'yaml'
getVar = YAML.load_file(configFile) 

NUMBER_OF_MANAGERS=getVar['NUMBER_OF_MANAGERS']
NUMBER_OF_WORKERS=getVar['NUMBER_OF_WORKERS']
MEMORY=getVar['MEMORY']
NUMBER_CPUS=getVar['NUMBER_CPUS']
IP_NETWORK=getVar['IP_NETWORK']
BEGINN_IP_NETWORK = IP_NETWORK.split('.')[0...-1].join('.')
VAGRANTFILE_API_VERSION = getVar['VAGRANTFILE_API_VERSION']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = getVar['VM_BOX']
  config.vm.box_version = getVar['BOX_VERSION']
  config.vm.provider 'virtualbox' do |v|
    # Linked clone is supported from version 1.8.0.
    # For more informations refer to the the following link:
    # https://www.vagrantup.com/docs/providers/virtualbox/configuration.html#linked-clones
    v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
  end
  
  ########################################################################
  #     Create the first manager, the main Manager where Swarm 
  #     will be initialized  
  ########################################################################
  config.vm.define "manager1" do |node|
    # Define the hostname
    node.vm.hostname = "manager1"
    node.vm.network "private_network", ip: BEGINN_IP_NETWORK + "." + "100"
  end

  ########################################################################
  #       Add other managers: Manager 2, Manager 3 ...    
  ########################################################################
  (2..NUMBER_OF_MANAGERS).each do |mgrNumber|
    _MANAGER_NAME = "manager#{mgrNumber}"
    config.vm.define _MANAGER_NAME do |node|
      # Define the hostname
      node.vm.hostname = _MANAGER_NAME
      node.vm.network "private_network", ip: BEGINN_IP_NETWORK + "." + "#{99+mgrNumber}"
    end
  end  
  # 
  ########################################################################
  #  Create Worker machines: worker1, worker2, worker3 ...
  ########################################################################
  (1..NUMBER_OF_WORKERS).each do |workerNumber|
    _WORKER_NAME = "worker#{workerNumber}"
    config.vm.define _WORKER_NAME do |node|
      # Define the hostname
      node.vm.hostname = _WORKER_NAME
      node.vm.network "private_network", ip: BEGINN_IP_NETWORK + "." + "#{149+workerNumber}"
    end
  end

  ########################################################################
  # ++++++  Configuration of the machines and Provisioning   +++++++++++++
  ########################################################################
  # Create synced file
  config.vm.synced_folder ".", "/ansible_prov"
  config.vm.provider "virtualbox" do |v|
    # Memory
    v.memory = MEMORY
    # Number of CPU
    v.cpus = NUMBER_CPUS
  end
  # Use Ansible to provision the Managers
  config.vm.provision "ansible_local" do |ansible|
    
    # If the compatibility is not defined, the following message will be printed:
    # --------------Vagrant has automatically selected the compatibility mode '2.0'
    # according to the Ansible version installed (2.9.14). Alternatively, the compatibility mode can be specified in your Vagrantfile:
    # https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode -------------------------

    # Define Ansible version
    ansible.compatibility_mode = "2.0"
    ansible.provisioning_path = "/ansible_prov"
    ansible.playbook = "provision/main-playbook.yml"
    # We add this extra var to use python3
    ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
  end
end